### ISSUE TITLE
Wayland protocols 404

### ISSUE THREAD

**Issue by colin-broderick** [rockchip-linux/buildroot#33]
```
>>> wayland-protocols 1.20 Downloading
--2021-02-01 15:11:01--  http://wayland.freedesktop.org/releases/wayland-protocols-1.20.tar.xz
Resolving wayland.freedesktop.org (wayland.freedesktop.org)... 35.227.58.183
Connecting to wayland.freedesktop.org (wayland.freedesktop.org)|35.227.58.183|:80... connected.
HTTP request sent, awaiting response... 308 Permanent Redirect
2021-02-01 15:11:01 ERROR 308: Permanent Redirect.

--2021-02-01 15:11:01--  http://sources.buildroot.net/wayland-protocols-1.20.tar.xz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.26.0.37, 172.67.72.56, 104.26.1.37, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.26.0.37|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-01 15:11:01 ERROR 404: Not Found.

package/pkg-generic.mk:166: recipe for target '/home/colin/firefly/proj/firefly-sdk/buildroot/output/rockchip_rk1808/build/wayland-protocols-1.20/.stamp_downloaded' failed
make: *** [/home/colin/firefly/proj/firefly-sdk/buildroot/output/rockchip_rk1808/build/wayland-protocols-1.20/.stamp_downloaded] Error 1
```

**Comment by colin-broderick** [comment]
Can apparently be worked around by visiting http://wayland.freedesktop.org/releases/wayland-protocols-1.20.tar.xz in a browser, which is not redirected, and downloads the file just fine. Put the downloads file in `buildroot/dls`

**Comment by JeffyCN** [comment]
looks like something wrong in your network setup or the freedesktop server.

it's fine now:
>>> wayland-protocols 1.20 Downloading
URL transformed to HTTPS due to an HSTS policy
--2021-02-04 00:56:09--  https://wayland.freedesktop.org/releases/wayland-protocols-1.20.tar.xz
Resolving wayland.freedesktop.org (wayland.freedesktop.org)... 35.227.58.183
Connecting to wayland.freedesktop.org (wayland.freedesktop.org)|35.227.58.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 111684 (109K) [application/x-xz]
Saving to: “/nvme/buildroot/output/rockchip_rk3399/build/.wayland-protocols-1.20.tar.xz.9X5tJn/output”

/nvme/buildroot/outp 100%[====================>] 109.07K   121KB/s    in 0.9s

2021-02-04 00:56:11 (121 KB/s) - “/nvme/buildroot/output/rockchip_rk3399/build/.wayland-protocols-1.20.tar.xz.9X5tJn/output” saved [111684/111684]
